# yaml-language-server: $schema=https://github.com/connerohnesorge/conclaude/releases/latest/download/conclaude-schema.json
# Conclaude Configuration Template
#
# This is a minimal example configuration file.
# For full documentation of all options, run: conclaude config --docs
# Or see the generated documentation from `cargo doc --open`

# Stop hook configuration - runs when Claude is about to stop
stop:
  # Structured command format with optional custom error messages
  # Each command can have its own error message, and control output display
  commands:
    - run: "spectr validate --all"
      showStdout: true
      showStderr: true
      message: "Spec validation (spectr validate --all) failed - please fix errors before continuing"
      maxOutputLines: 100
    - run: "nix develop -c lint"
      showStdout: false
      showStderr: false
      showCommand: true
      message: "Linting failed - please fix errors via individual delegation."
      maxOutputLines: 100
    - run: "nix develop -c tests"
      showStdout: true
      showStderr: true
      message: "Tests failed - please fix failing tests via individual delegation."
    - run: "cd docs && bun run build"
      showStdout: true
      showStderr: true
      message: "Docs build (cd docs && bun run build) failed - please fix errors"
    - run: "generate-docs"
      showStdout: false
      showStderr: false
      showCommand: true
      message: "Docs build (generate-docs) failed - please fix errors via individual delegation."
    - run: "generate-schema"
      showStdout: false
      showStderr: false
      showCommand: true
      message: "Docs build (generate-schema) failed - please fix errors via individual delegation."
  # Examples:
  # commands:
  #   - run: "echo 'Starting build...'"
  #     showStdout: true    # User/Claude sees: "Starting build..."
  #
  #   - run: "npm test"
  #     showStdout: true    # Show test results to user/Claude
  #     showStderr: true    # Show test errors to user/Claude
  #     message: "Tests failed - please fix failing tests before continuing"
  #     maxOutputLines: 100 # Limit output to last 100 lines (1-10000)
  #
  #   - run: "npm run build"
  #     showStderr: true    # Only show build errors to user/Claude, hide stdout
  #     message: "Build failed - please fix compilation errors"
  #     maxOutputLines: 50  # Limit build output to last 50 lines

  infinite: false
  infiniteMessage: "continue working on the task"

# Subagent stop hook - runs when subagents finish
subagentStop:
  commands: {}
  # Example:
  # coder:
  #   - run: "npm run lint"
  #     showStdout: true
  #     showCommand: true  # Show "Executing command X/Y: npm run lint" (default: true)
  #     message: "Linting failed"
  # test*:
  #   - run: "npm test"
  #     showStderr: true
  #     showCommand: false  # Hide the "Executing command..." line

# Pre-tool-use hook - file protection and tool validation
preToolUse:
  # Prevent files at repository root
  preventRootAdditions: true
  # Custom message for root additions block (supports {file_path} and {tool} placeholders)
  # Example: "Files must go in src/. Cannot create {file_path} using {tool}."
  preventRootAdditionsMessage: null

  # Protected files (glob patterns)
  uneditableFiles:
    - ".conclaude.yml"
    - ".conclaude.yaml"
  # Examples:
  # - "*.lock"
  # - pattern: ".env*"
  #   message: "Environment files contain secrets"
  #
  # Agent-specific protection examples (blocks specific subagents):
  # - pattern: "spectr/changes/**/tasks.jsonc"
  #   message: "Task files managed by orchestrator"
  #   agent: "coder"  # Only blocks coder subagent
  #
  # - pattern: "src/**/*.test.ts"
  #   message: "Test files managed by tester agent"
  #   agent: "code*"  # Blocks coder, coder-v2, etc.
  #
  # - pattern: "docs/**"
  #   agent: "*"  # Blocks all agents (same as omitting agent field)

  # Prevent editing git-ignored files
  preventUpdateGitIgnored: false

  # Tool usage rules
  toolUsageValidation: []
  # Example:
  # - tool: "Write"
  #   pattern: "**/*.js"
  #   action: "allow"
  # - tool: "Bash"
  #   commandPattern: "git push --force*"
  #   action: "block"
  #   message: "Force push not allowed"
  #
  # Agent-scoped rules (only apply to specific agents):
  # - tool: "Bash"
  #   pattern: ""
  #   commandPattern: "rm -rf *"
  #   action: "block"
  #   agent: "coder"
  #   message: "Coder agent cannot run destructive rm commands"
  # - tool: "Write"
  #   pattern: "**/*.test.ts"
  #   action: "block"
  #   agent: "coder"
  #   message: "Coder agent should not modify test files"
  # - tool: "*"
  #   pattern: "src/**"
  #   action: "block"
  #   agent: "test*"
  #   message: "Test agents cannot modify source files"
  #
  # Agent pattern examples:
  #   - agent: "coder"    # Exact match - only "coder" subagent
  #   - agent: "test*"    # Glob pattern - matches "tester", "test-runner"
  #   - agent: "*"        # Wildcard - matches all agents (default if omitted)

  # Directories where additions are prevented
  preventAdditions: []
  # Example: ["dist", "build"]

# System notifications
notifications:
  enabled: false
  hooks: [] # ["*"] for all, or ["Stop", "PreToolUse"]
  showErrors: false
  showSuccess: false
  showSystemEvents: true
# Permission request hook - auto-approve/deny tools
# Uncomment to enable:
#
# permissionRequest:
#   default: deny  # "allow" or "deny"
#   allow:
#     - "Read"
#     - "Glob"
#     - "Grep"
#     - "Edit"
#     - "Write"
#   deny:
#     - "BashOutput"
#     - "KillShell"

# User prompt submit hook - context injection and command execution
# Automatically prepends context when prompts match patterns
# Uncomment to enable:
#
# userPromptSubmit:
#   contextRules:
#     # Pattern-based context injection
#     - pattern: "sidebar"
#       prompt: |
#         Make sure to read @.claude/contexts/sidebar.md before proceeding.
#
#     # Multiple patterns with regex alternation
#     - pattern: "auth|login|authentication"
#       prompt: |
#         Review the authentication patterns in @.claude/contexts/auth.md
#
#     # Case-insensitive matching (using regex flag)
#     - pattern: "(?i)database|sql|query"
#       prompt: |
#         Follow the database conventions in @.claude/contexts/database.md
#
#     # Disable a rule temporarily
#     - pattern: "test"
#       prompt: "Run tests before proceeding"
#       enabled: false
#
#     # Explicit case-insensitive flag
#     - pattern: "api"
#       prompt: "Check API documentation first"
#       caseInsensitive: true
#
#   # Command execution (runs after contextRules processing)
#   # Commands are observational - they cannot block prompt processing
#   commands:
#     # Run for all prompts (no pattern)
#     - run: ".claude/scripts/log-prompt.sh"
#       showCommand: false
#
#     # Run only for prompts matching pattern (regex)
#     - pattern: "deploy|release|ship"
#       run: ".claude/scripts/notify-slack.sh"
#       showCommand: false
#
#     # Run with output display options
#     - pattern: "(?i)sql|database"
#       run: ".claude/scripts/check-db-access.sh"
#       showStdout: true
#       timeout: 30
#
#   # Environment variables available to commands:
#   # - CONCLAUDE_USER_PROMPT: The user's input text
#   # - CONCLAUDE_SESSION_ID: Current session ID
#   # - CONCLAUDE_CWD: Current working directory
#   # - CONCLAUDE_CONFIG_DIR: Directory containing .conclaude.yaml
#   # - CONCLAUDE_HOOK_EVENT: Always "UserPromptSubmit"
